# fly.toml app configuration file generated for checkers-game-app on 2026-02-15T20:04:50-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'checkers-game-app'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
