"""Initial

Revision ID: 553c04465c6d
Revises: 
Create Date: 2026-02-17 02:03:31.095965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '553c04465c6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table exists to avoid errors on existing DBs
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'games' in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('board_state', sa.JSON(), nullable=False),
        sa.Column('current_turn', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('winner', sa.String(), nullable=True),
        sa.Column('red_player_id', sa.String(), nullable=True),
        sa.Column('black_player_id', sa.String(), nullable=True),
        sa.Column('red_player_name', sa.String(), nullable=True),
        sa.Column('black_player_name', sa.String(), nullable=True),
        sa.Column('last_move', sa.JSON(), nullable=True),
        sa.Column('active_piece', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
