"""Add draw_timer column

Revision ID: 81e2fb85546d
Revises: eeafc6d1ec72
Create Date: 2026-02-17 03:36:39.012717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e2fb85546d'
down_revision: Union[str, Sequence[str], None] = 'eeafc6d1ec72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('draw_timer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'draw_timer')
    # ### end Alembic commands ###
