"""Add draw_offer column

Revision ID: eeafc6d1ec72
Revises: c64802188f7a
Create Date: 2026-02-17 02:41:26.358996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeafc6d1ec72'
down_revision: Union[str, Sequence[str], None] = 'c64802188f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('draw_offer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'draw_offer')
    # ### end Alembic commands ###
